# -*- coding: utf-8 -*-
"""SMA_Statictics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GWMCf1NtKC82a5eK-0OiQREvfWGQDBSr
"""

from google.colab import drive
drive.mount('/content/gdrive')

!cd "/content/gdrive/MyDrive/SMA_DATASETS/Assignment-1/"

import networkx as nx
dol = nx.read_gml("/content/gdrive/MyDrive/SMA_DATASETS/Assignment-1/dolphins.gml")



print(nx.info(dol))
print("Average path length is  : ", nx.average_shortest_path_length(dol))
average = nx.average_clustering(dol)
print("Clustering coefficient here is : ", average)
print("Stats for Dolphin")


kg = nx.read_gml("/content/gdrive/MyDrive/SMA_DATASETS/Assignment-1/karate.gml", label='id')
print(nx.info(kg))
print("Average path length is : ", nx.average_shortest_path_length(kg))
average = nx.average_clustering(kg)
print("Clustering coefficient here is: ", average)
print("Stats for Karate")



f = open("/content/gdrive/MyDrive/SMA_DATASETS/Assignment-1/jazz.net","r")
lines = f.readlines()
f.close()
nf = open("jazz.net","w")
for i in lines:
    if i != lines[0] and i != lines[1] and i != lines[2]:
        nf.write(i)
nf.close()
jg = nx.read_weighted_edgelist("/content/gdrive/MyDrive/SMA_DATASETS/Assignment-1/jazz.net")
print(nx.info(jg))
print("Average path length is: ", nx.average_shortest_path_length(jg))
average = nx.average_clustering(jg)
print("Clustering coefficient here is : ", average)
print("Stats for Jazz")



